# Site settings
title: SCATE
tag_text: Enabling Machine-actionable Semantics for Comparative Analyses of Trait Evolution
description: Website for Enabling Machine Actionable Semantics for Comparative Analyses of Trait Evolution (SCATE), an NSF-funded project
url: "https://scate.phenoscape.org"
baseurl: ""

font-awesome-include: true # make this false if you don't need font-awesome

# Build settings
markdown: kramdown

exclude: ["README.md"]
